### ISSUE TITLE
[usvg] Does not build if `export` feature is enabled without `filter` feature.

### ISSUE THREAD

**Issue by reknih** [RazrFalcon/resvg#489]
When depending on `usvg` with the `export` feature enabled, the `filter` feature must also be enabled for the crate to build. Otherwise, `Cargo.toml` configs like below will create a string of build errors.

```toml
[dependencies]
usvg = { version = "0.19", default-features = false, features = ["text", "export"] }
```

Instead, one would expect this to either be possible or the `export` feature to enable the `filter` feature as well.
