### ISSUE TITLE
font-family:monospace

### ISSUE THREAD

**Issue by igormironchik** [RazrFalcon/resvg#915]
What font `resvg` will use on Linux for the following CSS?

```css
.guage-text{font-size:40px;font-family:monospace;text-align:center}
```

On my openSUSE Tumbleweed SVG is not rendered properly due to missing text with the above class.

Thank you.
